2 Major changes has been applied to Intan RHD2000 Evaluation Board Interface program.

  1) Added LFP Scope option

  2) Added Probe Display option
  
  LFP Scope Option:
      This function is analagous to the Spike Scope option in the original software with following changes applied on:
      
        - Time interval is expanded to [-50ms, 200ms] instead of [-1ms, 2ms] in order to include the LFP responses.
        
        - 2 Buttons, Mean LFP, Each LFP is added to act as a toggle function between display settings of the LFPs.
        
        - 2 Plots can be seen on the right side. Top plot is for the digital input used for triggering, bottom plot is the lfp response
        
        - LFP Analysis button is added for temporal lfp analysis. When clicked new dialog appears. From this dialog, changes in the   
        minimum point of the mean LFP can be observed through time, samples will be taken as frequently as selected from scrollbars. Also,
        Errorbar checkbox enables the errorbar display of the analysis, Errorbar is generated by calculating the standard deviation of the
        LFPs from the mean response. 
        
  Probe Display Option:
      This function is generated for detailed display for the probe being used in the recording. It is designed for displaying single   
      probe at a time.
      
        - There is a default probe registered in the code it can be selected directly. Other types of probes can be loaded by the LOAD 
         Button. In order to load a probe, the .dat file for that probe should be generated with ProbeFileGenerator program also added to 
         this respiratory. After the generation of the probe's .dat file. By using Load Probe button it can be loaded to the main program. 
         
        - The currently selected channel is marked as red in the display options and also highlighted in the right waveform plot. In order 
        to select new channel, clicking to either waveforms plots in the left and probe in the right would suffice.
        
        - Grouping the electrodes from bottom to top size is also posible by using the grouping options scrollbar.
        
      
